packages:
  branch_codenames:
    master: trusty-unstable
    production: trusty-stable

jobs:
  runit-common:
    builder: "make"
    base: "quay.io/madebymany/build-bases:trusty"
    build_depends:
      - runit
      - postfix
    packages:
      - type: debian
        name: runit-common
        depends:
          - runit
          - postfix
        repos:
          - composed-public
        promote_through:
          - unstable
          - stable
        target: install
