software_groups: &software
  - "base"

packages:
  branch_codenames:
    master: unstable
    production: stable

jobs:
  runit_common:
    software_groups: *software
    builder: "make"
    base: "ubuntu:12.04"
    packages:
      - type: debian
        name: runit-common
        depends:
          - runit
          - postfix
        repos:
          - mxm-public
        promote_through:
          - unstable
          - stable
        target: install
