software_groups: &software
  - "base"
jobs:
  runit_common:
    software_groups: *software
    builder: "make"
    base: "ubuntu:12.04"
    packages:
      - type: debian
        name: runit-common
        depends:
          - runit
        repos:
          - mxm
        target: install
